spring.application.name=hospital

# Configuración de conexión a la Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/ProyecFinal?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tu_password

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true